%  HDR = bdf2biosig_events(HDR [,Mode])   
%
% INPUT:
%   HDR is the header structure generated by SOPEN, SLOAD or mexSLOAD
%    from loading a Biosemi (BDF) file.
%    Specifically, HDR.BDF.ANNONS contains the info of the status channel. 
%   Mode [default = 4]
%    determines how the BDF status channel is converted into 
%     the event table HDR.EVENT. Currently, the following modes are 
%    supported: 
%     1: epoching information is derived from bit17
%        only lower 8 bits are supported
%     2: suggested decoding if standardized event codes (according to 
%        .../biosig/doc/eventcodes.txt) are used  
%     3: Trigger Input 1-15, raising and falling edges
%     4: [default] Trigger Input 1-15, raising edges
%     5: Trigger input 1-8, raising and falling edges are considered
%     6: Trigger input 1-8, only raising edges are considered
%     7: bit-based decoding 
%    99: not recommended, because it could break some functionality in BioSig 
% Output:     
%   HDR.EVENT contains the generated Event table.      




[HDR,H1,h2] = sopen(input_bdffile);

HDR_events = bdf2biosig_events(HDR,7);
        
% Only keep every other event (rising edges) and convert samples to time
output_rising = [HDR_events.EVENT.POS(1:2:end)/HDR.SampleRate HDR_events.EVENT.TYP(1:2:end)];
 
% Keeps all events (rising and falling edges)   
output_allevents = [HDR_events.EVENT.POS/HDR.SampleRate HDR_events.EVENT.TYP];